apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: global
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./p-cluster-01/global
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  prune: true
  validation: client
