apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/infrastructure/sources
  - ../../base/infrastructure/kubed
patchesStrategicMerge:
  - kubed-values.yaml
