apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
spec:
  releaseName: kubed
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
      version: "v0.12.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    enableAnalytics: true
